(defpackage #:stripe
  (:use :cl)
  (:local-nicknames
   (#:alex #:alexandria)
   (#:jzon #:com.inuoe.jzon))
  ;; common
  (:export
   #:*api-version*
   #:*api-key*
   #:*webhook-secret*)
  ;; conditions
  (:export
   #:stripe-error
   #:account-already-exists
   #:account-country-invalid-address
   #:account-invalid
   #:account-number-invalid
   #:alipay-upgrade-required
   #:amount-too-large
   #:amount-too-small
   #:api-key-expired
   #:balance-insufficient
   #:bank-account-exists
   #:bank-account-unusable
   #:bank-account-unverified
   #:bitcoin-upgrade-required
   #:card-declined
   #:charge-already-captured
   #:charge-already-refunded
   #:charge-disputed
   #:charge-exceeds-source-limit
   #:charge-expired-for-capture
   #:country-unsupported
   #:coupon-expired
   #:customer-max-subscriptions
   #:email-invalid
   #:expired-card
   #:idempotency-key-in-use
   #:incorrect-cvc
   #:incorrect-number
   #:incorrect-zip
   #:instant-payouts-unsupported
   #:invalid-card-type
   #:invalid-charge-amount
   #:invalid-cvc
   #:invalid-expiry-month
   #:invalid-expiry-year
   #:invalid-number
   #:invalid-source-usage
   #:invoice-no-customer-line-items
   #:invoice-no-subscription-line-items
   #:invoice-not-editable
   #:invoice-upcoming-none
   #:livemode-mismatch
   #:missing
   #:not-allowed-on-standard-account
   #:order-creation-failed
   #:order-required-settings
   #:order-status-invalid
   #:order-upstream-timeout
   #:parameter-invalid-empty
   #:parameter-invalid-integer
   #:parameter-invalid-string-blank
   #:parameter-invalid-string-empty
   #:parameter-missing
   #:parameter-unknown
   #:parameters-exclusive
   #:payment-intent-authentication-failure
   #:payment-intent-incompatible-payment-method
   #:payment-intent-invalid-parameter
   #:payment-intent-payment-attempt-failed
   #:payment-intent-unexpected-state
   #:payment-intent-unactivated
   #:payment-method-unexpected-state
   #:payouts-not-allowed
   #:platform-api-key-expired
   #:postal-code-invalid
   #:processing-error
   #:product-inactive
   #:rate-limit
   #:resource-already-exists
   #:resource-missing
   #:routing-number-invalid
   #:secret-key-required
   #:sepa-unsupported-account
   #:setup-attempt-failed
   #:setup-attempt-unexpected-state
   #:shipping-calculation-failed
   #:state-unsupported
   #:tax-id-invalid
   #:taxes-calculation-failed
   #:testmode-charges-only
   #:tls-version-unsupported
   #:token-already-used
   #:token-in-use
   #:transfers-not-allowed
   #:upstream-order-creation-failed
   #:url-invalid
   #:webhook-invalid-header
   #:webhook-no-valid-signature
   #:webhook-not-signed
   #:webhook-timestamp-too-old)
  (:export
   #:construct-webhook-event
   #:parse-signature-header
   #:validate-webhook-payload))
